# Generated by Django 5.1.4 on 2026-03-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_site_admin',
            field=models.BooleanField(default=False),
        ),
    ]
