# Generated by Django 5.1.15 on 2026-03-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_notification_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_format',
            field=models.CharField(blank=True, default='MM/DD/YYYY', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='number_locale',
            field=models.CharField(blank=True, default='en-US', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='time_format',
            field=models.CharField(blank=True, default='12h', max_length=4),
        ),
    ]
