# Generated by Django 5.1.15 on 2026-03-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_site_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='close_editor_on_enter',
            field=models.BooleanField(default=False),
        ),
    ]
