# Generated by Django 5.1.15 on 2026-03-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_has_completed_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notif_board_invite',
            field=models.BooleanField(default=True),
        ),
    ]
