# Generated by Django 5.2.12 on 2026-04-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_unique_username_ci'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('boards', '0042_add_card_version'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('can_access_all_content', True)), fields=['can_access_all_content'], name='user_can_access_all_idx'),
        ),
    ]
