# Generated by Django 5.1.15 on 2026-04-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_can_access_all_content_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitelink',
            name='use_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
