# Generated by Django 5.1.15 on 2026-09-14 14:26
#
# #1110 — scope personal access tokens.
#
# Both columns are nullable with no backfill, so this is a metadata-only
# ADD COLUMN on PostgreSQL 11+ and safe for a zero-downtime deploy. Existing
# rows keep scopes = NULL, which is the "legacy" state: full REST authority
# exactly as before this migration, but never accepted where an mcp:* scope is
# required. There is deliberately NO data migration assigning scopes to
# existing tokens — silently narrowing a live credential would break running
# integrations, and silently widening one would defeat the change.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_invite_link_redemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccesstoken',
            name='last_used_scope',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='personalaccesstoken',
            name='scopes',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
