# Generated by Django 5.2.13 on 2026-09-16 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add maintenance mode to the SiteSetting singleton (#783).

    Deliberately a plain, atomic migration: it adds two *defaulted* columns and
    no index and no constraint, so the concurrent-build rule in
    docs/development/database-migrations.md does not apply — that rule covers
    AddIndex/AddConstraint, db_index=True, unique=True, Alter*Together and raw
    CREATE INDEX, none of which appear here. The MaxLengthValidator on
    maintenance_message is a Python-level validator, not a database CHECK, so it
    emits no DDL either. `site_settings` also holds exactly one row (pk=1), so
    the ACCESS EXCLUSIVE lock an AddField takes is held for microseconds against
    a single-row table.

    Both columns carry a default, per the zero-downtime rule that a new column
    must never be NOT NULL without one. maintenance_mode defaults to False so
    an existing install is behaviorally unchanged after upgrading.
    """

    dependencies = [
        ('accounts', '0026_pat_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='maintenance_message',
            field=models.TextField(blank=True, default='', help_text='Plain-text notice shown to users while maintenance mode is active. Blank uses the built-in default.', validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='When True, non-admin write requests are rejected with 503 and all users see a maintenance notice.'),
        ),
    ]
