# Generated by Django 5.2.17 on 2026-09-30 01:10
# Hand-edited per #1222: swapped the autodetector's plain AddIndex for the
# concurrent wrapper, since `users` is a populated table (see
# docs/development/database-migrations.md).

import django.db.models.functions.text
from django.db import migrations, models

from visiban.db_operations import AddIndexConcurrently


class Migration(migrations.Migration):

    # Required: CREATE INDEX CONCURRENTLY cannot run inside a transaction, and
    # Django wraps every migration in one by default.
    atomic = False

    dependencies = [
        ('account', '0009_emailaddress_unique_primary_email'),
        ('accounts', '0032_user_pending_email_addr_idx'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('boards', '0061_add_card_external_ref'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='user',
            index=models.Index(django.db.models.functions.text.Upper('email'), name='user_email_upper_idx'),
        ),
    ]
