# Generated by Django 5.2.17 on 2026-10-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_user_email_notif_comment_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitelink',
            name='delivery',
            field=models.CharField(choices=[('link', 'Link'), ('email', 'Email')], db_default='link', default='link', max_length=8),
        ),
    ]
