# Generated by Django 5.1.15 on 2026-03-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_groupinvitelink_extras_grouplabel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinvitelink',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('collaborator', 'Collaborator'), ('viewer', 'Viewer')], default='member', max_length=16),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('collaborator', 'Collaborator'), ('viewer', 'Viewer')], default='member', max_length=16),
        ),
    ]
