# Generated by Django 5.1.15 on 2026-03-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_groupfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
