# Generated by Django 5.2.13 on 2026-04-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_remove_invite_link_token_plaintext'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvitelink',
            name='single_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupinvitelink',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
