# Generated by Django 5.1.15 on 2026-04-15 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_group_invite_link_single_use'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groupinvitelink',
            constraint=models.CheckConstraint(condition=models.Q(('single_use', True), ('used_at__isnull', True), _connector='OR'), name='group_invite_link_used_at_requires_single_use'),
        ),
    ]
