# Generated by Django 5.2.17 on 2026-10-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_group_invite_link_used_at_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvitelink',
            name='delivery',
            field=models.CharField(choices=[('link', 'Link'), ('email', 'Email')], default='link', max_length=8),
        ),
    ]
