# Generated by Django 5.1.4 on 2026-03-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='column',
            name='weight_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
