# Generated by Django 5.1.4 on 2026-03-06 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_add_weight_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('priority_change', 'Priority changed'), ('weight_change', 'Weight changed'), ('assignee_change', 'Assignee changed'), ('label_change', 'Labels changed'), ('description_change', 'Description changed'), ('comment_added', 'Comment added'), ('attachment_added', 'Attachment added'), ('attachment_deleted', 'Attachment deleted')], max_length=30)),
                ('from_value', models.TextField(blank=True)),
                ('to_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='boards.card')),
            ],
            options={
                'db_table': 'card_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
