# Generated by Django 5.1.4 on 2026-03-06 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_rename_customer_to_swimlane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimlane',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimlanes', to='boards.board'),
        ),
    ]
