# Generated by Django 5.1.4 on 2026-03-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_board_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardactivity',
            name='event_type',
            field=models.CharField(choices=[('priority_change', 'Priority changed'), ('weight_change', 'Weight changed'), ('assignee_change', 'Assignee changed'), ('label_change', 'Labels changed'), ('description_change', 'Description changed'), ('comment_added', 'Comment added'), ('attachment_added', 'Attachment added'), ('attachment_deleted', 'Attachment deleted'), ('title_change', 'Title changed'), ('checklist_item_added', 'Checklist item added'), ('checklist_item_checked', 'Checklist item checked'), ('checklist_item_unchecked', 'Checklist item unchecked'), ('checklist_item_deleted', 'Checklist item deleted')], max_length=30),
        ),
    ]
