# Generated by Django 5.1.4 on 2026-03-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_alter_cardactivity_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('collaborator', 'Collaborator'), ('viewer', 'Viewer')], default='member', max_length=20),
        ),
    ]
