# Generated by Django 5.1.15 on 2026-03-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0020_card_mentioned_user_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='close_editor_on_enter',
        ),
    ]
