# Generated by Django 6.0.3 on 2026-03-19 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0023_seed_board_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='enforce_wip_limits',
            field=models.BooleanField(default=False, help_text='When enabled, card moves into a column at or over its WIP limit are blocked with a 409 response. Board admins can override with ?force=true.'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['board', 'column', 'archived_at'], name='card_board_col_archived_idx'),
        ),
    ]
