# Generated by Django 5.1.15 on 2026-03-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0025_alter_cardactivity_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='enforce_weight_limits',
            field=models.BooleanField(default=False, help_text='When enabled, card moves into a column that would exceed its weight budget are blocked with a 409 response. Board admins can override with ?force=true.'),
        ),
    ]
