# Generated by Django 5.1.15 on 2026-03-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0026_add_enforce_weight_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.CharField(blank=True, choices=[('assigned', 'assigned'), ('mentioned', 'mentioned'), ('card_moved', 'card moved'), ('stale', 'stale')], default='', max_length=32),
        ),
    ]
