# Generated by Django 5.1.15 on 2026-03-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0027_alter_notification_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='enforce_weight_limits',
            field=models.BooleanField(default=True, help_text='When enabled, card moves into a column that would exceed its weight budget are blocked with a 409 response. Board admins can override with ?force=true.'),
        ),
        migrations.AlterField(
            model_name='board',
            name='enforce_wip_limits',
            field=models.BooleanField(default=True, help_text='When enabled, card moves into a column at or over its WIP limit are blocked with a 409 response. Board admins can override with ?force=true.'),
        ),
    ]
