# Generated by Django 5.1.15 on 2026-03-24 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0030_card_trigram_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='stale_warning_pct',
            field=models.PositiveSmallIntegerField(default=50, help_text='Percentage of staleness_threshold_days at which heatmap cells turn yellow. At 100% of the threshold they turn red. Must be 0–100.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
