# Generated by Django 5.1.15 on 2026-03-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0036_cardmovement_type_and_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmembership',
            name='is_moderator',
            field=models.BooleanField(default=False, help_text="Grants content-moderation rights (delete/archive others' content) without full admin."),
        ),
    ]
