# Generated by Django 5.1.15 on 2026-03-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0038_add_notification_cardmovement_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.CharField(blank=True, choices=[('assigned', 'assigned'), ('mentioned', 'mentioned'), ('card_moved', 'card moved'), ('stale', 'stale'), ('board_invite', 'board invite')], default='', max_length=32),
        ),
    ]
