# Generated by Django 5.1.15 on 2026-04-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0041_alter_notification_action_type_no_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
