# Generated by Django 5.1.15 on 2026-04-16 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0044_cardchecklist_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cardactivity',
            index=models.Index(fields=['card', '-created_at'], name='activity_card_created_idx'),
        ),
    ]
