# Generated by Django 5.1.15 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0044_cardchecklist_created_by'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cardcomment',
            index=models.Index(fields=['card', 'created_at'], name='comment_card_created_idx'),
        ),
        migrations.AddIndex(
            model_name='cardactivity',
            index=models.Index(fields=['card', '-created_at'], name='activity_card_created_idx'),
        ),
    ]
