# Generated by Django 5.2.13 on 2026-09-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0051_board_card_density'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='show_wip_at_limit',
            field=models.BooleanField(default=False, help_text="When enabled, a column's header stat row shows a calm 'WIP n/n' indicator (in place of the normal card count) once the column's card count exactly equals its wip_limit (#973). Purely ambient — does not affect move enforcement, which is controlled by enforce_wip_limits / enforce_wip_hard. Off by default so existing boards are unchanged."),
        ),
    ]
