# Generated by Django 5.2.13 on 2026-09-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    """Create the append-only board change feed table (#1114).

    Left ``atomic`` (i.e. not ``atomic = False``) on purpose. The concurrent-DDL
    rule in CLAUDE.md exists because ``AddIndex`` on an *existing* table takes
    ``ACCESS EXCLUSIVE`` for the whole build — on ``cards`` that is an outage.
    ``board_events`` is created by this migration, so both of its indexes are
    built on a table no session can yet see and there is nothing to lock out.
    Keeping the migration transactional is strictly safer here: ``atomic=False``
    has no rollback, and a half-created table is worse than a retry.

    Nothing is added to ``cards`` or ``boards``. The feed references a board by a
    plain ``board_id`` integer rather than a ForeignKey — see ``BoardEvent``'s
    docstring for why an append-only table must not carry a cascading relation.
    """

    dependencies = [
        ('boards', '0055_add_card_board_updated_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.BigIntegerField(help_text='Board this event belongs to. Deliberately not a ForeignKey — see the model docstring.')),
                ('event', models.CharField(help_text="Event type, exactly as broadcast over the WebSocket (e.g. 'card.moved').", max_length=64)),
                ('data', models.JSONField(default=dict, help_text="The broadcast payload, verbatim — identical to the WebSocket frame's 'data' object.")),
                ('actor_id', models.BigIntegerField(blank=True, help_text='User who caused the event; NULL for events with no authenticated actor.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'board_events',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['board_id', 'id'], name='bev_board_id_idx'), models.Index(fields=['created_at'], name='bev_created_idx')],
            },
        ),
    ]
