# Generated by Django 5.2.13 on 2026-09-15 12:51

import boards.uid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add the per-board custom field schema and the per-card values (#371).

    Zero-downtime: safe, and deliberately atomic. Both operations are
    ``CreateModel`` — a new table takes no lock anything else can contend for,
    and the unique constraints and the ``(field_definition, value)`` index are
    built as part of the create rather than as separate ``AddIndex`` /
    ``AlterUniqueTogether`` operations, so no index is ever built against a
    table that has rows or readers. That is why this migration keeps Django's
    default ``atomic = True`` instead of the ``atomic = False`` +
    ``AddIndexConcurrently`` pattern that ``docs/development/database-migrations.md``
    requires for an index on an existing table: there is nothing here to build
    concurrently, and ``atomic = False`` would trade a rollback for nothing.

    Nothing on ``cards`` or ``boards`` is altered — the relationship is carried
    by FK columns on the two new tables, so no existing table is touched.
    """

    dependencies = [
        ('boards', '0056_board_event_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=boards.uid._generate_uid, editable=False, max_length=16, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox')], default='text', max_length=20)),
                ('choices_json', models.JSONField(blank=True, default=list, help_text="Permitted values, used only when field_type is 'dropdown'. Stored on the definition rather than in a separate table so the choices are always loaded with the field they belong to.")),
                ('position', models.IntegerField(default=0)),
                ('show_on_card', models.BooleanField(default=False, help_text="Pin this field's value to the card face. Max 2 per board.")),
                ('is_required', models.BooleanField(default=False, help_text='Declared but NOT enforced in v1 — the column exists so the flag can be set and read before enforcement lands. Do not add enforcement without a release note: it would turn existing valid card writes into 400s.')),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='boards.board')),
            ],
            options={
                'db_table': 'custom_field_definitions',
                'ordering': ['position', 'id'],
                'unique_together': {('board', 'name'), ('board', 'position')},
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='boards.card')),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='boards.customfielddefinition')),
            ],
            options={
                'db_table': 'custom_field_values',
                'indexes': [models.Index(fields=['field_definition', 'value'], name='cfv_definition_value_idx')],
                'unique_together': {('card', 'field_definition')},
            },
        ),
    ]
