# Generated by Django 5.2.13 on 2026-09-15 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add the typed card-to-card relation table (#449).

    Zero-downtime: safe, and deliberately atomic. The only operation is a
    ``CreateModel`` — a new table takes no lock anything else can contend for,
    and the ``cardrel_to_type_idx`` index, the ``unique_together`` constraint
    and the ``cardrel_no_self_relation`` check are all built as part of the
    create rather than as separate ``AddIndex`` / ``AlterUniqueTogether`` /
    ``AddConstraint`` operations, so no index or constraint is ever built
    against a table that has rows or readers.

    That is why this migration keeps Django's default ``atomic = True`` instead
    of the ``atomic = False`` + ``AddIndexConcurrently`` pattern that
    ``docs/development/database-migrations.md`` requires for an index on an
    *existing* table — see that document's rule table, which lists
    ``db_index=True`` / ``unique=True`` inside ``CreateModel`` as explicitly
    exempt ("the table is new — no rows, no readers"). There is nothing here to
    build concurrently, and ``atomic = False`` would trade away rollback for
    nothing.

    Nothing on ``cards`` is altered: the relationship is carried by two FK
    columns on this new table, so no existing table is touched.
    """

    dependencies = [
        ('boards', '0057_add_custom_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('blocks', 'Blocks'), ('relates_to', 'Relates to')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_card_relations', to=settings.AUTH_USER_MODEL)),
                ('from_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='boards.card')),
                ('to_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='boards.card')),
            ],
            options={
                'db_table': 'card_relations',
                'indexes': [models.Index(fields=['to_card', 'relation_type'], name='cardrel_to_type_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_card', models.F('to_card')), _negated=True), name='cardrel_no_self_relation')],
                'unique_together': {('from_card', 'to_card', 'relation_type')},
            },
        ),
    ]
