# Generated by Django 5.2.17 on 2026-09-20 23:51

import boards.uid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add the per-board swimlane field schema and the per-row values (#1140).

    Zero-downtime: safe, and deliberately atomic, for exactly the reasons
    ``0057_add_custom_fields`` gives for the card-level pair. Both operations
    are ``CreateModel`` — a new table takes no lock anything else can contend
    for, and both unique constraints plus the ``(field_definition, value)``
    index are built as part of the create rather than as separate ``AddIndex``
    / ``AlterUniqueTogether`` operations, so no index is ever built against a
    table that has rows or readers. Hence Django's default ``atomic = True``
    rather than the ``atomic = False`` + ``visiban.db_operations`` pattern that
    ``docs/development/database-migrations.md`` requires for an index on an
    *existing* table: there is nothing here to build concurrently, and
    ``atomic = False`` would trade away rollback for nothing.

    Nothing on ``swimlanes``, ``boards``, ``cards`` or the card-level
    ``custom_field_values`` is altered. That is the payoff of giving row fields
    their own tables instead of adding a ``target_type`` discriminator to the
    card pair: the discriminator would have meant altering a unique constraint
    and adding a check constraint on a populated table, which this project's
    migration rules turn into three migrations, two of them without rollback.
    """

    dependencies = [
        ('boards', '0058_add_card_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwimlaneCustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=boards.uid._generate_uid, editable=False, max_length=16, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox')], default='text', max_length=20)),
                ('choices_json', models.JSONField(blank=True, default=list, help_text="Permitted values, used only when field_type is 'dropdown'. Stored on the definition rather than in a separate table so the choices are always loaded with the field they belong to.")),
                ('position', models.IntegerField(default=0)),
                ('show_on_row', models.BooleanField(default=False, help_text="Pin this field's value to the swimlane row header. Max 3 per board.")),
                ('is_admin_only', models.BooleanField(default=True, help_text="Serve this field's values only to board admins, reusing the existing SwimlaneSerializer/SwimlaneAdminSerializer split rather than adding a second visibility rule. Defaults to True because the default is not symmetrically reversible: loosening a field later is an additive, per-field admin action, while tightening one would change what an existing install already exposes — a 1.0 contract break. Rows carry entity data (this model was called Customer until migration 0005), so the safe default is the closed one.")),
                ('is_required', models.BooleanField(default=False, help_text='Declared but NOT enforced in v1 — the column exists so the flag can be set and read before enforcement lands. Do not add enforcement without a release note: it would turn existing valid swimlane writes into 400s.')),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimlane_custom_field_definitions', to='boards.board')),
            ],
            options={
                'db_table': 'swimlane_custom_field_definitions',
                'ordering': ['position', 'id'],
                'unique_together': {('board', 'name'), ('board', 'position')},
            },
        ),
        migrations.CreateModel(
            name='SwimlaneCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='boards.swimlanecustomfielddefinition')),
                ('swimlane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='boards.swimlane')),
            ],
            options={
                'db_table': 'swimlane_custom_field_values',
                'indexes': [models.Index(fields=['field_definition', 'value'], name='scfv_definition_value_idx')],
                'unique_together': {('swimlane', 'field_definition')},
            },
        ),
    ]
