# Generated by Django 5.2.17 on 2026-09-27 02:58

import boards.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add the card external-ref (MR/PR link) table (#352).

    Zero-downtime: safe, and deliberately atomic. The only operation is a
    ``CreateModel`` — the ``cardextref_provider_ref_idx`` index and the
    OneToOne's unique index are built as part of the create, against a table
    with no rows or readers, which ``docs/development/database-migrations.md``
    lists as exempt from the concurrent-build rule. Nothing on ``cards`` is
    altered.
    """

    dependencies = [
        ('boards', '0060_notification_due_soon_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardExternalRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gitlab', 'GitLab'), ('github', 'GitHub'), ('other', 'Other')], max_length=16)),
                ('ref', models.CharField(max_length=255, validators=[boards.models.validate_external_ref_ref])),
                ('url', models.CharField(max_length=2048, validators=[boards.models.validate_external_ref_url])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_ref', to='boards.card')),
            ],
            options={
                'db_table': 'card_external_refs',
                'indexes': [models.Index(fields=['provider', 'ref'], name='cardextref_provider_ref_idx')],
            },
        ),
    ]
