# Generated by Django 5.2.17 on 2026-10-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0066_custom_field_choice_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='enforce_weight_limits',
            field=models.BooleanField(default=True, help_text="When enabled, moving, creating, or restoring a card into a column that would exceed its weight budget, or raising a card's weight with PATCH/PUT, is blocked with a 409 response, as is saving a card in the Django admin. Board admins can override with ?force=true (not in the Django admin). Board import is not checked."),
        ),
        migrations.AlterField(
            model_name='board',
            name='enforce_wip_limits',
            field=models.BooleanField(default=True, help_text='When enabled, moving, creating, or restoring a card into a column at or over its WIP limit is blocked with a 409 response, as is saving a card in the Django admin. Board admins can override with ?force=true (not in the Django admin). Board import is not checked.'),
        ),
    ]
