# Generated by Django 5.2.17 on 2026-10-06 22:12
#
# Board invites (#1444): two new tables. Constraints and indexes declared
# inside CreateModel are built on an empty table, so no concurrent operation
# is needed (docs/development/database-migrations.md).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0067_enforce_limits_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardInviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('prefix', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('role', models.CharField(choices=[('member', 'Member'), ('collaborator', 'Collaborator'), ('viewer', 'Viewer')], default='member', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('single_use', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('delivery', models.CharField(choices=[('link', 'Link'), ('email', 'Email')], default='link', max_length=8)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='boards.board')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_board_invite_links', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_board_invite_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'board_invite_links',
                'constraints': [models.CheckConstraint(condition=models.Q(('single_use', True), ('used_at__isnull', True), _connector='OR'), name='board_invite_link_used_at_requires_single_use')],
            },
        ),
        migrations.CreateModel(
            name='BoardInviteRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_granted', models.CharField(max_length=20)),
                ('membership_created', models.BooleanField(default=False)),
                ('via', models.CharField(choices=[('join', 'Join'), ('registration', 'Registration')], max_length=16)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='boards.boardinvitelink')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_invite_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'board_invite_redemptions',
                'constraints': [models.UniqueConstraint(fields=('invite', 'user'), name='board_invite_redemption_unique_user')],
            },
        ),
    ]
