# Generated by Django 5.2.17 on 2026-10-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0068_board_invite_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='show_row_chip_field_names',
            field=models.BooleanField(db_default=True, default=True, help_text="When enabled (the default), pinned custom-field chips on a swimlane row label each value with its field name, e.g. 'AD: Diane Foster' (#1418). When disabled, row chips show the value alone; the name stays in the chip tooltip, for screen readers, and in the row's field list. Checkbox fields always show their name. Board-level admin setting, not a per-viewer preference; card-face chips are unaffected."),
        ),
    ]
