# Generated by Django 5.2.17 on 2026-10-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0069_board_show_row_chip_field_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardexportlog',
            name='row_count',
            field=models.PositiveIntegerField(help_text='Number of rows exported: cards for a board export, movements for a movement-history export.'),
        ),
    ]
