# Generated by Django 5.2.13 on 2026-06-06 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0051_board_card_density'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LensConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab')], max_length=16)),
                ('repo_slug', models.CharField(max_length=255)),
                ('column_dim', models.CharField(default='status', max_length=32)),
                ('swimlane_dim', models.CharField(default='milestone', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lens_connection', to='boards.board')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
