# Generated by Django 5.2.15 on 2026-06-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_lens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lensconnection',
            name='column_dim',
            field=models.CharField(default='pipeline', max_length=32),
        ),
    ]
