"""Integrity checks for the committed ``sample-boards/*.json`` templates.

The files are generated by ``backend/boards/seed_data/generate_seed_data.py``;
these tests fail if a regeneration (or a hand edit) reintroduces cards that
contradict their column, or extra card-creation columns.
"""

import json
import re
from pathlib import Path

from django.test import SimpleTestCase

SAMPLE_DIR = Path(__file__).resolve().parents[3] / "sample-boards"
TEMPLATES = sorted(p for p in SAMPLE_DIR.glob("*.json") if p.stem != "demo_board")

# (title regex, columns the card may legitimately sit in) per template.
STAGE_EXPECTATIONS = {
    "customer_success": [
        (r"-- (Kickoff|Onboarding)", {"Onboarding"}),
        (r"-- Adoption", {"Adoption"}),
        (r"-- Healthy", {"Healthy"}),
        (r"-- Expansion", {"Expansion"}),
        (r"-- Renewal", {"Renewal"}),
        (r"-- Churned", {"Churned"}),
    ],
    "hiring_recruiting": [
        (r"^Phone screen", {"Phone Screen"}),
        (r"^Technical screen", {"Technical Screen"}),
        (r"^Panel interview", {"Interview"}),
        (r"^Reference check", {"Reference Check"}),
        (r"^Offer", {"Offer Extended", "Hired"}),
    ],
}


class SampleBoardIntegrityTests(SimpleTestCase):
    def test_templates_found(self):
        self.assertEqual(len(TEMPLATES), 10)

    def test_only_first_column_allows_card_creation(self):
        for path in TEMPLATES:
            data = json.loads(path.read_text(encoding="utf-8"))
            creatable = [c["name"] for c in data["columns"] if c.get("allow_card_creation")]
            self.assertEqual(creatable, [data["columns"][0]["name"]], path.name)

    def test_every_card_references_a_real_column_and_swimlane(self):
        for path in TEMPLATES:
            data = json.loads(path.read_text(encoding="utf-8"))
            cols = {c["name"] for c in data["columns"]}
            lanes = {s["name"] for s in data["swimlanes"]}
            for card in data["cards"]:
                self.assertIn(card["column"], cols, f"{path.name}: {card['title']}")
                self.assertIn(card["swimlane"], lanes, f"{path.name}: {card['title']}")
                self.assertEqual(card["movements"][-1]["to_column"], card["column"], card["title"])

    def test_stage_titles_sit_in_their_stage_column(self):
        for slug, rules in STAGE_EXPECTATIONS.items():
            data = json.loads((SAMPLE_DIR / f"{slug}.json").read_text(encoding="utf-8"))
            for card in data["cards"]:
                for rx, allowed in rules:
                    if re.search(rx, card["title"], re.IGNORECASE):
                        self.assertIn(card["column"], allowed, f"{slug}: {card['title']}")
                        break
