"""Integrity checks for the committed ``backend/boards/sample_boards/*.json`` templates.

The JSON files and ``manifest.json`` live inside the backend package so the
backend image ships them (#1452); the CSVs are repo-only in ``sample-boards/``.
The files are generated by ``backend/boards/seed_data/generate_seed_data.py``;
these tests fail if a regeneration (or a hand edit) reintroduces cards that
contradict their column, or extra card-creation columns — and, since #1447,
if a committed file drifts from the generator, or if importing a sample
through the real endpoint loses any of what it carries.
"""

import collections
import contextlib
import hashlib
import importlib.util
import io
import json
import re
import sys
import tempfile
from pathlib import Path
from unittest import mock

from django.test import SimpleTestCase, TestCase
from rest_framework.test import APIClient

from accounts.models import User
from boards.models import (
    Board, CardActivity, CardComment, CardExternalRef, CardMovement,
    CustomFieldDefinition, CustomFieldValue, SwimlaneCustomFieldDefinition,
    SwimlaneCustomFieldValue,
)
from boards.views.import_export import BoardImportThrottle

SAMPLE_DIR = Path(__file__).resolve().parents[1] / "sample_boards"
CSV_DIR = Path(__file__).resolve().parents[3] / "sample-boards"
SEED_DIR = Path(__file__).resolve().parents[1] / "seed_data"
REPO_ROOT = Path(__file__).resolve().parents[3]
MANIFEST = json.loads((SAMPLE_DIR / "manifest.json").read_text(encoding="utf-8"))
TEMPLATES = sorted(p for p in SAMPLE_DIR.glob("*.json") if p.name != "manifest.json")

# Every CardActivity type the JSON format can carry. Attachments are the
# exception: the format has no attachment payload, so a sample entry would
# point at a file that does not exist.
CARRIED_EVENT_TYPES = {
    e.value for e in CardActivity.EventType
} - {CardActivity.EventType.ATTACHMENT_ADDED, CardActivity.EventType.ATTACHMENT_DELETED}

# (title regex, columns the card may legitimately sit in) per template.
STAGE_EXPECTATIONS = {
    "customer_success": [
        (r"-- (Kickoff|Onboarding)", {"Onboarding"}),
        (r"-- Adoption", {"Adoption"}),
        (r"-- Healthy", {"Healthy"}),
        (r"-- Expansion", {"Expansion"}),
        (r"-- Renewal", {"Renewal"}),
        (r"-- Churned", {"Churned"}),
    ],
    "hiring_recruiting": [
        (r"^Phone screen", {"Phone Screen"}),
        (r"^Technical screen", {"Technical Screen"}),
        (r"^Panel interview", {"Interview"}),
        (r"^Reference check", {"Reference Check"}),
        (r"^Offer", {"Offer Extended", "Hired"}),
    ],
}


class SampleBoardIntegrityTests(SimpleTestCase):
    def test_templates_found(self):
        self.assertEqual([p.stem for p in TEMPLATES], sorted(e["id"] for e in MANIFEST))
        self.assertIn("sales_overlay", [p.stem for p in TEMPLATES])

    def test_only_first_column_allows_card_creation(self):
        for path in TEMPLATES:
            data = json.loads(path.read_text(encoding="utf-8"))
            creatable = [c["name"] for c in data["columns"] if c.get("allow_card_creation")]
            self.assertEqual(creatable, [data["columns"][0]["name"]], path.name)

    def test_every_card_references_a_real_column_and_swimlane(self):
        for path in TEMPLATES:
            data = json.loads(path.read_text(encoding="utf-8"))
            cols = {c["name"] for c in data["columns"]}
            lanes = {s["name"] for s in data["swimlanes"]}
            for card in data["cards"]:
                self.assertIn(card["column"], cols, f"{path.name}: {card['title']}")
                self.assertIn(card["swimlane"], lanes, f"{path.name}: {card['title']}")
                self.assertEqual(card["movements"][-1]["to_column"], card["column"], card["title"])

    def test_stage_titles_sit_in_their_stage_column(self):
        for slug, rules in STAGE_EXPECTATIONS.items():
            data = json.loads((SAMPLE_DIR / f"{slug}.json").read_text(encoding="utf-8"))
            for card in data["cards"]:
                for rx, allowed in rules:
                    if re.search(rx, card["title"], re.IGNORECASE):
                        self.assertIn(card["column"], allowed, f"{slug}: {card['title']}")
                        break


def _load(path):
    return json.loads(path.read_text(encoding="utf-8"))


@contextlib.contextmanager
def _generator():
    """The generator module, with ``seed_data`` importable for its part-2 loaders."""
    sys.path.insert(0, str(SEED_DIR))
    try:
        spec = importlib.util.spec_from_file_location(
            "generate_seed_data_under_test", SEED_DIR / "generate_seed_data.py",
        )
        gen = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(gen)
        yield gen
    finally:
        sys.path.remove(str(SEED_DIR))
        sys.modules.pop("generate_seed_data", None)


class SampleBoardRegenerationTests(SimpleTestCase):
    def test_committed_files_match_the_generator(self):
        """A hand edit, or a generator change committed without regenerating, fails here."""
        with _generator() as gen, tempfile.TemporaryDirectory() as json_out, \
                tempfile.TemporaryDirectory() as csv_out, mock.patch("builtins.print"):
            gen.main(json_out, csv_out)
            for out, committed in ((json_out, SAMPLE_DIR), (csv_out, CSV_DIR)):
                for name in sorted(p.name for p in Path(out).iterdir()):
                    self.assertEqual(
                        (Path(out) / name).read_bytes(), (committed / name).read_bytes(),
                        f"{committed.name}/{name} is stale; run generate_seed_data.py",
                    )

    def test_generated_docs_tables_are_current(self):
        with _generator() as gen:
            highlights = {
                g["slug"]: g["highlights"]
                for g in gen._load_module("sample_gallery.py", "sample_gallery").GALLERY
            }
            for page, table in (
                (gen.DOCS_PAGE, gen.render_docs_table(MANIFEST, highlights)),
                (gen.README_PAGE, gen.render_readme_table(MANIFEST)),
            ):
                text = Path(page).read_text(encoding="utf-8")
                self.assertEqual(
                    text, gen.splice_table(text, table),
                    f"{Path(page).name} sample table is stale; run generate_seed_data.py",
                )


class SampleManifestTests(SimpleTestCase):
    """The manifest is what the in-app gallery and the docs are built from (#1452)."""

    def test_manifest_matches_the_files_on_disk(self):
        self.assertEqual(sorted(e["file"] for e in MANIFEST), sorted(p.name for p in TEMPLATES))
        self.assertEqual({p.name for p in SAMPLE_DIR.iterdir()}, {*(p.name for p in TEMPLATES), "manifest.json"})

    def test_entries_are_complete_and_ordered(self):
        keys = {"id", "title", "description", "swimlane_theme", "card_count", "includes",
                "file", "order", "sha256", "schema_version"}
        for e in MANIFEST:
            self.assertEqual(set(e), keys, e["id"])
            self.assertRegex(e["id"], r"^[a-z0-9_]+$")
            self.assertEqual(e["file"], f"{e['id']}.json")
        orders = [e["order"] for e in MANIFEST]
        self.assertEqual(orders, sorted(set(orders)), "order must be unique and the manifest sorted by it")
        self.assertEqual(len({e["id"] for e in MANIFEST}), len(MANIFEST))

    def test_sha256_matches_the_file_bytes(self):
        for e in MANIFEST:
            digest = hashlib.sha256((SAMPLE_DIR / e["file"]).read_bytes()).hexdigest()
            self.assertEqual(e["sha256"], digest, e["id"])

    def test_derived_fields_match_the_file_contents(self):
        for e in MANIFEST:
            data = _load(SAMPLE_DIR / e["file"])
            cards = data["cards"]
            with self.subTest(e["id"]):
                self.assertEqual(e["card_count"], sum(1 for c in cards if not c.get("archived_at")))
                self.assertEqual(e["schema_version"], data["schema_version"])
                self.assertEqual(e["title"], data["name"])
                self.assertEqual("labels" in e["includes"], any(c["labels"] for c in cards))
                self.assertEqual("checklists" in e["includes"], any(c["checklist"] for c in cards))
                self.assertEqual("comments" in e["includes"], any(c["comments"] for c in cards))
                self.assertEqual("history" in e["includes"], any(len(c["movements"]) > 1 for c in cards))

    def test_import_names_carry_no_template_prefix(self):
        for p in TEMPLATES:
            self.assertFalse(_load(p)["name"].startswith("Template:"), p.name)

    def test_samples_ship_inside_the_backend_build_context(self):
        """Compose, CI and Helm build the backend image with ``backend/`` as context."""
        backend = REPO_ROOT / "backend"
        self.assertTrue(SAMPLE_DIR.is_relative_to(backend))
        ignored = (backend / ".dockerignore").read_text(encoding="utf-8").splitlines()
        self.assertFalse(any(line.strip() in {"sample_boards", "sample_boards/", "*.json"} for line in ignored))


class SampleBoardFeatureCoverageTests(SimpleTestCase):
    """The samples exist to show the product off; these pin what they show."""

    def test_every_template_carries_the_1_2_board_features(self):
        for path in TEMPLATES:
            data = _load(path)
            with self.subTest(path.name):
                self.assertGreaterEqual(len(data["custom_fields"]), 6)
                self.assertGreaterEqual(len(data["swimlane_custom_fields"]), 3)
                self.assertTrue(any(c["wip_limit"] for c in data["columns"]))
                self.assertTrue(any(c.get("archived_at") for c in data["cards"]))
                self.assertTrue(all(cm.get("created_at") for c in data["cards"] for cm in c["comments"]))
                self.assertTrue(any(m["notes"] for c in data["cards"] for m in c["movements"]))
                self.assertTrue(any(f["is_admin_only"] for f in data["swimlane_custom_fields"]))
                for lane in data["swimlanes"]:
                    self.assertTrue(lane["custom_field_values"], lane["name"])
                    self.assertEqual(lane["contact_email"], "", lane["name"])

    def test_every_board_shows_exactly_one_column_over_its_wip_limit(self):
        """Enough to show the over-limit flag, not so many the board reads as broken."""
        for path in TEMPLATES:
            data = _load(path)
            live = collections.Counter(c["column"] for c in data["cards"] if not c.get("archived_at"))
            over = [c["name"] for c in data["columns"] if c["wip_limit"] and live[c["name"]] > c["wip_limit"]]
            self.assertEqual(len(over), 1, (path.name, over))
            self.assertTrue(any(c.get("weight_limit") for c in data["columns"]), path.name)

    def test_samples_together_use_every_field_type_and_event_type(self):
        field_types, event_types = set(), set()
        for path in TEMPLATES:
            data = _load(path)
            field_types |= {f["field_type"] for f in data["custom_fields"] + data["swimlane_custom_fields"]}
            event_types |= {a["event_type"] for c in data["cards"] for a in c["activities"]}
        self.assertEqual(field_types, {t.value for t in CustomFieldDefinition.FieldType})
        self.assertEqual(event_types, CARRIED_EVENT_TYPES)

    def test_sales_overlay_uses_every_card_field_type_and_the_row_field_maximum(self):
        data = _load(SAMPLE_DIR / "sales_overlay.json")
        self.assertEqual(
            {f["field_type"] for f in data["custom_fields"]},
            {t.value for t in CustomFieldDefinition.FieldType},
        )
        lane_fields = data["swimlane_custom_fields"]
        self.assertEqual(len(lane_fields), SwimlaneCustomFieldDefinition.MAX_PER_BOARD)
        self.assertEqual(
            sum(f["show_on_row"] for f in lane_fields), SwimlaneCustomFieldDefinition.MAX_PINNED_PER_BOARD,
        )
        self.assertEqual([f["name"] for f in lane_fields][:2], ["AD", "AE"])
        coverage = {s["name"]: s["custom_field_values"]["Coverage"] for s in data["swimlanes"]}
        self.assertEqual(collections.Counter(coverage.values()), {"Full": 8, "Partial": 1, "Gap": 1})

    def test_sales_overlay_org_shape(self):
        """Each AE reports to one AD, and each overlay AE always pairs with the same overlay SA."""
        lanes = [s["custom_field_values"] for s in _load(SAMPLE_DIR / "sales_overlay.json")["swimlanes"]]
        ad_of = collections.defaultdict(set)
        osa_of = collections.defaultdict(set)
        svc_of = collections.defaultdict(set)
        for v in lanes:
            ad_of[v["AE"]].add(v["AD"])
            svc_of[v["AD"]].add(v["SVC"])
            if v["OAE"] != "Unassigned":
                osa_of[v["OAE"]].add(v["OSA"])
        self.assertTrue(all(len(ads) == 1 for ads in ad_of.values()), ad_of)
        self.assertTrue(all(len(osas) == 1 for osas in osa_of.values()), osa_of)
        self.assertTrue(all(len(svcs) == 1 for svcs in svc_of.values()), svc_of)


class SampleBoardImportTests(TestCase):
    """Import every sample through the real endpoint and count what landed.

    The counts compare against the file, so a value the API refuses, a field
    the importer stops restoring, or a doubled history entry fails here
    rather than as a quietly thinner demo board.
    """

    def setUp(self):
        # Eleven imports in one test would trip the 10/hour import throttle.
        patcher = mock.patch.object(BoardImportThrottle, "allow_request", return_value=True)
        patcher.start()
        self.addCleanup(patcher.stop)
        self.client = APIClient()
        self.user = User.objects.create_user(username="importer", password="pass")
        for i in range(1, 6):
            User.objects.create_user(username=f"demo{i}", password="pass")
        self.client.force_authenticate(self.user)

    def _import(self, path):
        f = io.BytesIO(path.read_bytes())
        f.name = path.name
        resp = self.client.post("/api/v1/boards/import/", {"file": f}, format="multipart")
        self.assertEqual(resp.status_code, 201, (path.name, getattr(resp, "data", None)))
        return Board.objects.get(pk=resp.data["id"])

    def test_every_sample_imports_without_losing_anything(self):
        for path in TEMPLATES:
            data = _load(path)
            with self.subTest(path.name):
                board = self._import(path)
                cards = data["cards"]
                self.assertEqual(
                    CustomFieldDefinition.objects.filter(board=board).count(), len(data["custom_fields"]),
                )
                self.assertEqual(
                    SwimlaneCustomFieldDefinition.objects.filter(board=board).count(),
                    len(data["swimlane_custom_fields"]),
                )
                self.assertEqual(
                    CustomFieldValue.objects.filter(card__board=board).count(),
                    sum(len(c["custom_field_values"]) for c in cards),
                )
                self.assertEqual(
                    SwimlaneCustomFieldValue.objects.filter(swimlane__board=board).count(),
                    sum(len(s["custom_field_values"]) for s in data["swimlanes"]),
                )
                self.assertEqual(
                    CardExternalRef.objects.filter(card__board=board).count(),
                    sum(1 for c in cards if c.get("external_ref")),
                )
                self.assertEqual(
                    CardComment.objects.filter(card__board=board).count(),
                    sum(len(c["comments"]) for c in cards),
                )
                self.assertEqual(
                    CardMovement.objects.filter(card__board=board).count(),
                    sum(len(c["movements"]) for c in cards),
                )
                self.assertEqual(
                    board.cards.filter(archived_at__isnull=False).count(),
                    sum(1 for c in cards if c.get("archived_at")),
                )
                # Exactly the file's history: no synthetic label / checklist /
                # weight entries stacked on top of the recorded ones.
                self.assertEqual(
                    CardActivity.objects.filter(card__board=board).count(),
                    sum(len(c["activities"]) for c in cards),
                )

    def test_imported_values_are_stored_as_written(self):
        path = SAMPLE_DIR / "sales_overlay.json"
        data = _load(path)
        board = self._import(path)
        lane = data["swimlanes"][0]
        stored = {
            v.field_definition.name: v.value
            for v in SwimlaneCustomFieldValue.objects.filter(
                swimlane__board=board, swimlane__name=lane["name"],
            ).select_related("field_definition")
        }
        self.assertEqual(stored, lane["custom_field_values"])
        card = data["cards"][0]
        stored = {
            v.field_definition.name: v.value
            for v in CustomFieldValue.objects.filter(
                card__board=board, card__title=card["title"],
            ).select_related("field_definition")
        }
        self.assertEqual(stored, card["custom_field_values"])
