{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "visiban.fullname" . }}
  labels:
    {{- include "visiban.labels" . | nindent 4 }}
type: Opaque
stringData:
  django-secret-key: {{ .Values.secret.djangoSecretKey | quote }}
  database-url: {{ include "visiban.databaseUrl" . | quote }}
  google-client-id: {{ .Values.backend.oauth.google.clientId | quote }}
  google-client-secret: {{ .Values.backend.oauth.google.clientSecret | quote }}
  github-client-id: {{ .Values.backend.oauth.github.clientId | quote }}
  github-client-secret: {{ .Values.backend.oauth.github.clientSecret | quote }}
  gitlab-client-id: {{ .Values.backend.oauth.gitlab.clientId | quote }}
  gitlab-client-secret: {{ .Values.backend.oauth.gitlab.clientSecret | quote }}
  {{- if .Values.backend.oauth.oidc.serverUrl }}
  oidc-client-id: {{ .Values.backend.oauth.oidc.clientId | quote }}
  oidc-client-secret: {{ .Values.backend.oauth.oidc.clientSecret | quote }}
  {{- end }}
{{- end }}
